# Generated by Django 5.2.5 on 2025-08-13 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('EMPTY', 'EMPTY'), ('RENTED', 'RENTED'), ('MAINT', 'MAINT')], default='EMPTY', max_length=10)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.building')),
            ],
        ),
    ]
