# Generated by Django 5.2.5 on 2025-08-13 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('billing_cycle', models.CharField(default='MONTHLY', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('ENDED', 'ENDED'), ('SUSPENDED', 'SUSPENDED')], default='ACTIVE', max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('room',), name='uniq_active_contract_per_room')],
            },
        ),
    ]
